### ISSUE TITLE
Error In logic.h file

### ISSUE THREAD

**Issue by Prajwal5761** [Prajwal5761/Sport-Event-Management-#2]
Their is Some Syntax error in the logic.h file due to which it gives error 
please create new brach for solving the issue
![Screenshot 2024-10-10 191841](https://github.com/user-attachments/assets/fbf98814-6dbd-4877-82ff-a30b6150abe7)

**Comment by ajinkya4422** [comment]
Resolved the issue of logic.h file by solving the syntax errors.
