### ISSUE TITLE
Getting error in winner function not getting proper output.

### ISSUE THREAD

**Issue by ajinkya4422** [Prajwal5761/Sport-Event-Management-#3]
While calling winner function of athletics games the list is not printing properly. Find the issue and solve the error.
![Screenshot 2024-10-11 122504](https://github.com/user-attachments/assets/dac24346-e873-4e66-8d91-be5c595fe2f3)

**Comment by Prajwal5761** [comment]
I have resolved the issue in the logic.c file .this issue arise due to the some base pointing lines are miss in given file
![Screenshot 2024-10-11 123834](https://github.com/user-attachments/assets/f62f594f-1943-4ad5-9bb0-47614d2a620f)
